# Generated by Django 3.0.4 on 2020-05-03 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videotitle', models.CharField(max_length=40)),
                ('videodesc', models.TextField()),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
